### PR TITLE
Booking f

### PR DESCRIPTION
**Pull request by sashakaverina**
simple_form with a datepicker on experience #show page

### CODE REVIEW

**Comment by sashakaverina** [comment]
need to implement choosing a date on datepicker --> show div with a selected date instead of today/tomorro
Screen Shot 2022-01-06 at 15 45 07
w

**Comment by sashakaverina** [comment]
- on change, flatpickr updates the date below (need to work on a format tho)

**Comment by dmbf29** [comment]
oh my god what happened here @sashakaverina 😆

**Comment by dmbf29** [comment]
⚠️ Don't merge. Working on a fix for this

**Comment by dmbf29** [comment]
I'm going to close this one because of the `.git` issues and the recreation of the flatpickr in #27 . @sashakaverina 🙇

**Pull request closed without merging**
